title: Sungkwang Mun
description: "Personal Website of Sungkwang Mun, Ph.D."
url: "https://sungkwang.github.io"

collections:
  publications:
    output: false
  software:
    output: false
  projects:
    output: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
